title: '29歳で未経験から約1年間でフリーランスエンジニアに転職したロードマップ'
summary: '2020年3月に仕事を辞め,自宅を守りながらプログラミングを勉強し,11月に初めて自分のスキルでお金を稼いだ話と,その結果として,誰でも未経験からフリーランスエンジニアになれるのかを元教育者や心理学の知見を交えた観点で考察します.また,何をどのように学んでいったかもなるべく細かく書いてます.'
topics: ['フリーランス', 'React', 'フロントエンドエンジニア']
published: true
price: 1200 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
# chapters:
#   - example1
#   - example2
